[project]
name="yatzy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python=">=3.9"
dependencies = [
    "nbdev>=2.4.6",
]

[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"
